### ISSUE TITLE
React example

### ISSUE THREAD

**Issue by atanaskanchev** [nordigen/nordigen-bank-ui#1]
@victory-sokolov @robbernan  I am struggling to use the library with React. Could you please add a sample code snippet?

**Comment by etaytch** [comment]
Hey @robbernan ,
Any news on a React sample?

**Comment by Martyneris** [comment]
any updates on React usage examples?

**Comment by AnthonyNahas** [comment]
I would love to integrate nordigen bank ui with my angular app...

**Comment by the-homeless-god** [comment]
@adroneleh could you share an open repository with an example?
