### ISSUE TITLE
Nordigen css file is messing up with external page elements

### ISSUE THREAD

**Issue by dgillier** [nordigen/nordigen-bank-ui#21]
Hello,

I'm trying to use this UI library within a HTML page (laravel & tailwinds blade based) but all text outside of your modal is being reduced in size...

Probably something in your css file is messing up...

**Comment by victory-sokolov** [comment]
Hello,

Could you please upgrade to never version `1.4.0`.
We made some changes to how base font-size is being set-up.
Please let us know if this solves your problem
