### ISSUE TITLE
Node Package has faulty imports

### ISSUE THREAD

**Issue by DanielTrontsios** [nordigen/nordigen-bank-ui#24]
importing the npm package you have provided does not allow importing the library.

the import throws the error below:
`Error: Cannot find module '/app/available_modules/1663606340000/nordigen-bank-ui/src/selector.js'. Please verify that the package.json has a valid "main" entry`

You can find this error yourself using the [runkit](https://npm.runkit.com/nordigen-bank-ui)

**Comment by victory-sokolov** [comment]
Hello! Main entry should be fixed, i'm not sure why are you trying to use browser based library in Node environment.
As well this library is ment to be used via `script` tag, we will release soon React package that will be more flexible
