### ISSUE TITLE
Can't fetch /api/v2/institutions/ with JAVASCRIPT (no CORS support)

### ISSUE THREAD

**Issue by MetallianFR68** [nordigen/nordigen-bank-ui#3]
Providing a javascript library is great but the API can't really be used with javascript.

If you try to fetch() with CORS enabled, the API refuses the connection (no cors support)
if you try to fetch() with {method: 'no-cors'} you can't set the ContentType to 'application/json' and the API refuses the connection with an ERROR 415

NORDIGEN should enable CORS

**Comment by victory-sokolov** [comment]
Hello!

We don't have enabled CORS on the server-side for security reasons, we are not planning to enable them in a near future.
If you would like to use our API, you should do it on the server-side, for that purpose we have created [nordige-node ](https://github.com/nordigen/nordigen-node)package to easily interact with our API, then you could make requests from the client to your local node server.

**Comment by martinpengellyphillips** [comment]
Just encountered this myself. I was trying to create a serverless application that used Nordigen and it would have been good to be able to call from the browser directly.

**Comment by JokTronki** [comment]
The solution to this issue is to create a local proxy and call the API via proxy.

Example from my Nuxt3/vite project:
file: nuxt.config.ts
```
vite: {
    server: {
      proxy: {
        "/nord": {
          target: "https://ob.nordigen.com/",
          changeOrigin: true,
          rewrite: (path) => path.replace(/^\/nord/, ""),
        },
      },
      cors: {
        origin: ["https://ob.nordigen.com"],
        methods: ["GET", "PUT", "POST"],
        allowedHeaders: ["Content-Type", "Authorization"],
      },
    },
  },
```

file: MyPage.vue
```
<script setup>
const { data: accessData, refresh: refreshData } = await useFetch(
  "/nord/api/v2/token/new/",
  requestOptions
);
</script>
```
